### ISSUE TITLE
Order is still created if customer returns from payment window, without completing

### ISSUE THREAD

**Issue by aarhusgregersen** [RBech/Quickpay_Payment#3]
If a customer proceeds with an order all the way to the payment window and then decides they need additional items on that order (or they don't want anything at all), an order is still created within the magento back-end.

Naturally you can just delete this, but it infers issues with missing order numbers, and if it occurs often enough could indicate embezzlement, which no business (should) want to.

I am not sure if it has to do with Quickpay_Payment plugin, but it appears to it, in development.

I am fairly new to magento so I may be wrong.

**Comment by RBech** [comment]
This is part of the magento order creation flow, once the customer hits "place order" in checkout the order is created in the backend as seen here: [http://www.mexbs.com/wp-content/uploads/2014/01/magento-order-state-status-flow.png](url) 

The current implementation ensures that orders cancelled in the payment window gets marked as cancelled which is the magento equivalent of a deleted order :)

**Comment by aarhusgregersen** [comment]
Native magento it is then! I came to the wrong place, but I do appreciate the help :-)
