### ISSUE TITLE
Order Page is broken after installing this.

### ISSUE THREAD

**Issue by burhandodhy** [RBech/Quickpay_Payment#4]
Hi,

I have installed this extension and now my order page is broken. http://prntscr.com/dqxjj3 . 

How i  can revert it back ?? 

Thanks

**Comment by RBech** [comment]
You can of course remove the extension to completely revert it, but I would gladly help you troubleshoot why this is happening if you want? Usually it has to do with other extensions interfering

**Comment by RBech** [comment]
@burhandodhy did you figure out the cause? :)

**Comment by RBech** [comment]
@burhandodhy since you haven't returned I assume you figured out a solution, I'll close the issue for now but feel free to reopen it if you still need help
