### ISSUE TITLE
Error in Fraudprobability.php

### ISSUE THREAD

**Issue by cnl2860** [RBech/Quickpay_Payment#6]
You have a typo in:
/app/code/community/Quickpay/Payment/Model/Sales/Order/Grid/Fraudprobability.php

The first line says:
**_<?phpclass_** Quickpay_Payment_Model_Sales_Order_Grid_Fraudprobability
Should be:
_**<?php class**_ Quickpay_Payment_Model_Sales_Order_Grid_Fraudprobability

The error has at least been there since oktober 2015. Because that was the first time i wrote to you about it.

**Comment by RBech** [comment]
hi @cnl2860 :)

I took over maintenance of the extension last autumn and was not informed about the typo, thanks for bringing it to my attention though, I will release a patched version shortly :)
